### PR TITLE
Refactoring code to improve testability

### PR DESCRIPTION
**Pull request by JohnnyEstilles**
Addressing issue #19.

@rafinskipg, please DO NOT MERGE yet. I still have a few more tests to go.

To run the tests use: `npm test`.
To run the coverage report use: `npm run coverage` (name sure you install istanbul globally with `npm install -g istanbul`)

As of right now this is the coverage report.

```
=============================== Coverage summary ===============================
Statements   : 95.38% ( 227/238 )
Branches     : 85.48% ( 53/62 )
Functions    : 92.68% ( 38/41 )
Lines        : 95.38% ( 227/238 )
================================================================================
```

Will more commits with the remaining tests soon. I'll advise when I'm done so you can revise and merge.

### CODE REVIEW

**Comment by JohnnyEstilles** [comment]
Sorry about that last Travis failure. I was missing the commit with the `sinon` and `sinon-chai` deps.

**Comment by rafinskipg** [comment]
Hi @JohnnyEstilles The pull request looks good, :+1:  Thank you for your effort! This will add a lot of value to the project.

Right now the build is failing, i can pull the code tonight and see what's happening. 

You deserve a medal, sir!

**Comment by JohnnyEstilles** [comment]
Just realized that the tests for `git_changelog.js` were polluting the following tests. I just fixed the issue. :-)

Just a few more tests to go.

**Comment by JohnnyEstilles** [comment]
No medal yet. I'm not done. LOL

**Comment by JohnnyEstilles** [comment]
Coverage now at ...

```
=============================== Coverage summary ===============================
Statements   : 96.64% ( 230/238 )
Branches     : 93.55% ( 58/62 )
Functions    : 90.24% ( 37/41 )
Lines        : 96.64% ( 230/238 )
================================================================================
```

We will probably not achieve 100% coverage, but we will be close. :-)

**Comment by rafinskipg** [comment]
can we merge it? :santa:

**Comment by JohnnyEstilles** [comment]
Patience "kemosabe"! I'm not done yet. :-)

**Comment by JohnnyEstilles** [comment]
Found bug that caused this failure (see #21). Will include fix in this PR.

**Comment by JohnnyEstilles** [comment]
@rafinskipg ... the PR is now stable. It can be merged. There are still some tests I want to add, but I can submit a separate PR for that.

**Comment by rafinskipg** [comment]
thats awesome
merging

**Pull request merged**
