### PR TITLE
feat: Add nomerge option to ignore merge commit msg

### PR DESCRIPTION
**Pull request by domrongpon-tanpaibul**
It seems to me that this option is no longer exist in the v1.0.x so I would like to add this feature back.

### CODE REVIEW

**Comment by seivan** [comment]
@domrongpon-tanpaibul Unless I've misunderstood you, there is an `.changelogrc` that dictates what gets parsed. Last time I checked the default one seems to have "merge commits" as an option. Your `.changelogrc` could remove it.

**Comment by domrongpon-tanpaibul** [comment]
@seivan Um. Do you have a sample of .changelogrc? I also check from README and `git-changelog -h`, there is no mention about no merge option.

**Comment by seivan** [comment]
@domrongpon-tanpaibul Again, I might not understand correctly, but I would suspect this is something related to "omitting" stuff from the changelog.

https://github.com/rafinskipg/git-changelog/blob/master/.changelogrc#L40-L42

If you don't want merge commit messages, you could have a changelog that omits them.

**Comment by domrongpon-tanpaibul** [comment]
@seivan Right, that'd work. I will check it out more. One more question if you don't mind, is it possible to group the change log by tag version? Searching in issues and it seems that this feature is not implemented yet. 

Would you please advise?

**Comment by seivan** [comment]
@domrongpon-tanpaibul You should create a separate issue for that. Right of the bat, I'd say it's not currently possible, but I could be wrong.

**Comment by domrongpon-tanpaibul** [comment]
@seivan Thanks a lot. I'll close this PR as we don't need it.

**Pull request closed without merging**
