### PR TITLE
feat: commit template

### PR DESCRIPTION
**Pull request by rafinskipg**
Hey @glebcha , found this on my computer, i guess is not finished, i need to take a look and adapt to the new changes. 

I believe the idea was to be able to specify a commit template, this way the commit messages styles can be adapted for each user. I will take a look at it later on

### CODE REVIEW

**Comment by glebcha** [comment]
@rafinskipg I'll resolve conflicts in this branch.

**Comment by glebcha** [comment]
@rafinskipg can you review branch and take a decision on merge?

**Comment by rafinskipg** [comment]
lets take a look

**Comment by rafinskipg** [comment]
@glebcha please take a look again, i added the missing features:
now it loads the commit template and it works nicely!! great. People can customize the commits,

**Comment by glebcha** [comment]
@rafinskipg Totally great, can we merge it?

**Pull request merged**
